### PR TITLE
Update Travis config

### PR DESCRIPTION
**Pull request by pascalduez**
- Ensure tests run on node 4.2 (LTS) as well as latest stable version
- Ensure npm is up to date (latest fixes)
- Use Travis container based infrastructure (`sudo: false`)
- Minor speed improvement (`git: depth`)

### CODE REVIEW

**Comment by ziir** [comment]
Hey @pascalduez,

Thank you for this PR, I'm not too familiar with Travis CI, so I'm glad to discover new stuff.
I'm willing to merge this, there's just one thing I'm not too sure about :

> - Ensure npm is up to date (latest fixes)

From what I can see of "real-life" use of NPM, 3.x is not the default ... 
Most people are still on running on 2.x, and most project still require it, while breaking on 3.x.

Basically, I'm inclined to stay on 2.x unless I can see a real advantage to moving forward to 3.x.

> $ node --version
> v4.2.1
> $ npm --version
> 2.14.7

Extracted the Travis build of this very PR.

**Comment by pascalduez** [comment]
I was sure that you'd have make you raise an eyebrow :) 
Indeed not strictly necessary. 
It's just that on several projects it used to save us from many issues. 
On the other hand it can also bring new ones (especially with 3).

I'll remove it.

**Comment by pascalduez** [comment]
Removed the npm udpate thing, rebased.

**Comment by ziir** [comment]
:+1: Thank you!

**Pull request merged**
